language: go
sudo: false
branches:
  only:
    - main

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
  - "1.15"
  - "1.16"
  - "1.17"

install:
  - export GOPATH=$HOME/go
  - mkdir -p $GOPATH/src/ykzts.com/x
  - mv $TRAVIS_BUILD_DIR $GOPATH/src/ykzts.com/x/mirakurun
  - go get -d -t -v ykzts.com/x/mirakurun/...

script:
  - go test -v ykzts.com/x/mirakurun/...
